[package]
name = "termino-tui"
description = "Termino 终端俄罗斯方块"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "termino"
path = "src/main.rs"

[dependencies]
ratatui = "0.29.0"
termino-core.workspace = true

[dev-dependencies]
insta = "1.49.0"

[lints]
workspace = true
