[package]
name = "termino-tui"
description = "Termino 终端俄罗斯方块"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "termino"
path = "src/main.rs"

[dependencies]
directories = "6.0.0"
ratatui = "0.29.0"
rodio = { version = "0.21.1", default-features = false, features = ["playback"] }
serde = { version = "1.0.229", features = ["derive"] }
termino-core.workspace = true
toml = "1.1.7"

[dev-dependencies]
insta = "1.49.0"

[lints]
workspace = true
